<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2020/01/24 09:30:50

return array(
'crm' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=CRM_EDICOM',
  'username' => 'presencemedia',
  'password' => 'jRuMFjrn2dR3MsQt',
  'name' => 'crm',
)),

'bd_web' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=BD_EDICOM',
  'username' => 'presencemedia',
  'password' => 'jRuMFjrn2dR3MsQt',
  'name' => 'bd_web',
)),);
