<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/01/24 09:38:52
sfConfig::add(array(
  'mod_visite_planifiee_enabled' => true,
  'mod_visite_planifiee_view_class' => 'sfPHP',
));
