<?php
// auto-generated by sfCacheConfigHandler
// date: 2020/01/24 10:08:20
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

