<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/01/24 18:27:11
sfConfig::add(array(
  'mod_administration_enabled' => true,
  'mod_administration_view_class' => 'sfPHP',
));
