<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/01/24 09:47:42
sfConfig::add(array(
  'mod_planning_televente_enabled' => true,
  'mod_planning_televente_view_class' => 'sfPHP',
));
