<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/01/24 09:31:39
sfConfig::add(array(
  'mod_visite_effectuee_enabled' => true,
  'mod_visite_effectuee_view_class' => 'sfPHP',
));
