# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/07-Databases

all:


  crm:
    class: sfDoctrineDatabase
    param:
      dsn:      'mysql:host=localhost;dbname=CRM_EDICOM'
      username: presencemedia
      password: jRuMFjrn2dR3MsQt


  bd_web:
    class: sfDoctrineDatabase
    param:
      dsn:      'mysql:host=localhost;dbname=BD_EDICOM'
      username: presencemedia
      password: jRuMFjrn2dR3MsQt

